# Generated by Django 6.0.6 on 2026-07-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conseiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence', models.CharField(default='Agence Casablanca Centre', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DossierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100)),
                ('client_prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('revenu_mensuel', models.FloatField()),
                ('revolving_utilization', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('nb_open_credit_lines', models.IntegerField()),
                ('nb_real_estate_loans', models.IntegerField()),
                ('nb_dependents', models.IntegerField()),
                ('nb_30_59_days_late', models.IntegerField()),
                ('nb_60_89_days_late', models.IntegerField()),
                ('nb_90_days_late', models.IntegerField()),
                ('score_risque', models.FloatField()),
                ('niveau_risque', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='credit_scoring.conseiller')),
            ],
        ),
    ]
