# Generated by Django 6.0.6 on 2026-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conseiller',
            name='role',
            field=models.CharField(choices=[('conseiller', 'Conseiller'), ('admin', 'Administrateur')], default='conseiller', max_length=20),
        ),
    ]
