# Generated by Django 6.0.6 on 2026-07-17 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_scoring', '0002_conseiller_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_calcule', models.FloatField()),
                ('version_modele', models.CharField(default='xgboost_v1', max_length=50)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_scoring.conseiller')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='credit_scoring.dossiercredit')),
            ],
        ),
    ]
