# Generated by Django 6.0.6 on 2026-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_scoring', '0003_logscoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsMensuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(unique=True)),
                ('nb_dossiers', models.IntegerField()),
                ('score_moyen', models.FloatField()),
                ('nb_faible', models.IntegerField()),
                ('nb_modere', models.IntegerField()),
                ('nb_eleve', models.IntegerField()),
                ('date_calcul', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
