# Generated by Django 6.0.6 on 2026-07-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_scoring', '0004_statsmensuelles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimNiveauRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, unique=True)),
                ('couleur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DimTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('jour', models.IntegerField()),
                ('trimestre', models.IntegerField()),
                ('nom_mois', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FaitScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_risque', models.FloatField()),
                ('revenu_mensuel', models.FloatField()),
                ('debt_ratio', models.FloatField()),
                ('age_client', models.IntegerField()),
                ('conseiller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_scoring.conseiller')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_scoring.dossiercredit')),
                ('niveau_risque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_scoring.dimniveaurisque')),
                ('temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_scoring.dimtemps')),
            ],
        ),
    ]
